// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgMwaEA5c2_FlyTy8aNZTdLV6oOrX5oEk',
    appId: '1:476572740950:web:210a0435cd11140d7d7af7',
    messagingSenderId: '476572740950',
    projectId: 'tiktok-app-b85c8',
    authDomain: 'tiktok-app-b85c8.firebaseapp.com',
    storageBucket: 'tiktok-app-b85c8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy7K0ZBxKVzO8Vh8ZYGR3igXZDvKOU8OQ',
    appId: '1:476572740950:android:a7364cc6f470fe6e7d7af7',
    messagingSenderId: '476572740950',
    projectId: 'tiktok-app-b85c8',
    storageBucket: 'tiktok-app-b85c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-X0zB056IjtW4Et7V9bPfEaSB06D56Vs',
    appId: '1:476572740950:ios:237940445bd7bac97d7af7',
    messagingSenderId: '476572740950',
    projectId: 'tiktok-app-b85c8',
    storageBucket: 'tiktok-app-b85c8.appspot.com',
    iosBundleId: 'com.example.tiktokClone',
  );
}
